site_name: rk-boot
site_url: https://docs.rkdev.info
repo_name: rookie-ninja/rk-docs
repo_url: https://github.com/rookie-ninja/rk-docs

theme:
  name: material
  language: en
  features:
    - content.tabs.link
#    - toc.integrate
    - navigation.top
#    - navigation.sections
#    - navigation.expand

plugins:
  - glightbox
  - i18n:
      default_language: en
      languages:
        en:
          name: English
          build: true
        zh:
          name: 简体中文
          build: true
      nav_translations:
        zh:
          Overview: 概览
          Example: 例子
          Contribution: 贡献
          Guide: 指引
          Code of conduct: 贡献者公约
          Getting started: 快速开始
          Web Framework: Web 框架
          Cache: 缓存
          Local: 本地缓存
          Database: 数据库
          Plugins: 插件
          User guide: 用户指南
          Common API: 通用 API
          Auth: 权限
          API Docs: API 文档
          Prometheus client: Prometheus 客户端
          Middleware: 中间件
          Logging: 日志
          Tracing: 调用链
          Ratelimit: 限速
          Timeout: 超时
          Gzip: 压缩
          Config: 参数配置
          Embed: 嵌入式参数
          Environment variable: 环境变量
          Error type: 错误码管理
          App info: 应用信息
          Log: 日志管理
          Multiple entries: 启动多个服务
          Override boot: 覆盖启动参数
          Graceful shutdown: 优雅关闭
          Static file handler: 静态文件管理
          Trace with logs: 日志调用链
          File upload: 文件上传
          Compile proto: 编译 proto
          Custom route: 自定义路径
          Developer guide: 开发者指南
markdown_extensions:
  - attr_list
  - toc:
      permalink: "#"
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - 'Overview': 'index.md'
  - 'Example': 'example/index.md'
  - 'Getting started':
      - 'Web Framework':
        - 'gin-gonic/gin': 'getting-started/web/gin.md'
        - 'gRPC': 'getting-started/web/grpc.md'
        - 'labstack/echo': 'getting-started/web/echo.md'
        - 'gogf/gf': 'getting-started/web/gf.md'
        - 'gofiber/fiber': 'getting-started/web/fiber.md'
        - 'gorilla/mux': 'getting-started/web/mux.md'
        - 'zeromicro/go-zero': 'getting-started/web/zero.md'
      - 'Cache':
          - 'Local': 'getting-started/cache/local.md'
          - 'Redis': 'getting-started/cache/redis.md'
      - 'Database':
          - 'MySQL': 'getting-started/database/mysql.md'
          - 'PostgreSQL': 'getting-started/database/postgres.md'
          - 'Redis': 'getting-started/database/redis.md'
          - 'SQLite': 'getting-started/database/sqlite.md'
          - 'SqlServer': 'getting-started/database/sqlserver.md'
          - 'MongoDB': 'getting-started/database/mongodb.md'
          - 'ClickHouse': 'getting-started/database/clickhouse.md'
  - 'User guide':
      - 'gin-gonic/gin':
          - 'Swagger UI': 'user-guide/gin/sw.md'
          - 'Common API': 'user-guide/gin/common.md'
          - 'API Docs': 'user-guide/gin/doc.md'
          - 'PPROF': 'user-guide/gin/pprof.md'
          - 'Prometheus client': 'user-guide/gin/prom.md'
          - 'Config': 'user-guide/gin/config.md'
          - 'Embed': 'user-guide/gin/embed.md'
          - 'Environment variable': 'user-guide/gin/env.md'
          - 'Error type': 'user-guide/gin/error-type.md'
          - 'App info': 'user-guide/gin/info.md'
          - 'Log': 'user-guide/gin/logging.md'
          - 'Multiple entries': 'user-guide/gin/multiple-entries.md'
          - 'Override boot': 'user-guide/gin/override.md'
          - 'Graceful shutdown': 'user-guide/gin/shutdown-hook.md'
          - 'Static file handler': 'user-guide/gin/static-file-handler.md'
          - 'TLS': 'user-guide/gin/tls.md'
          - 'Trace with logs': 'user-guide/gin/trace-with-logs.md'
          - 'Middleware':
            - 'Auth': 'user-guide/gin/mid/auth.md'
            - 'Logging': 'user-guide/gin/mid/logging.md'
            - 'Prometheus': 'user-guide/gin/mid/prom.md'
            - 'Tracing': 'user-guide/gin/mid/tracing.md'
            - 'RequestId': 'user-guide/gin/mid/meta.md'
            - 'Ratelimit': 'user-guide/gin/mid/ratelimit.md'
            - 'Timeout': 'user-guide/gin/mid/timeout.md'
            - 'Gzip': 'user-guide/gin/mid/gzip.md'
            - 'JWT': 'user-guide/gin/mid/jwt.md'
            - 'CORS': 'user-guide/gin/mid/cors.md'
            - 'Secure': 'user-guide/gin/mid/secure.md'
            - 'CSRF': 'user-guide/gin/mid/csrf.md'
      - 'gRPC':
          - 'Swagger UI': 'user-guide/grpc/sw.md'
          - 'Common API': 'user-guide/grpc/common.md'
          - 'API Docs': 'user-guide/grpc/doc.md'
          - 'gRPC gateway': 'user-guide/grpc/gateway.md'
          - 'Compile proto': 'user-guide/grpc/buf.md'
          - 'Custom route': 'user-guide/grpc/custom-route.md'
          - 'PPROF': 'user-guide/grpc/pprof.md'
          - 'Prometheus client': 'user-guide/grpc/prom.md'
          - 'Config': 'user-guide/grpc/config.md'
          - 'Embed': 'user-guide/grpc/embed.md'
          - 'Environment variable': 'user-guide/grpc/env.md'
          - 'Error type': 'user-guide/grpc/error-type.md'
          - 'App info': 'user-guide/grpc/info.md'
          - 'Log': 'user-guide/grpc/logging.md'
          - 'Multiple entries': 'user-guide/grpc/multiple-entries.md'
          - 'Override boot': 'user-guide/grpc/override.md'
          - 'Graceful shutdown': 'user-guide/grpc/shutdown-hook.md'
          - 'Static file handler': 'user-guide/grpc/static-file-handler.md'
          - 'TLS': 'user-guide/grpc/tls.md'
          - 'File upload': 'user-guide/grpc/file-upload.md'
          - 'Trace with logs': 'user-guide/grpc/trace-with-logs.md'
          - 'Middleware':
              - 'Auth': 'user-guide/grpc/mid/auth.md'
              - 'Logging': 'user-guide/grpc/mid/logging.md'
              - 'Prometheus': 'user-guide/grpc/mid/prom.md'
              - 'Tracing': 'user-guide/grpc/mid/tracing.md'
              - 'RequestId': 'user-guide/grpc/mid/meta.md'
              - 'Ratelimit': 'user-guide/grpc/mid/ratelimit.md'
              - 'Timeout': 'user-guide/grpc/mid/timeout.md'
              - 'JWT': 'user-guide/grpc/mid/jwt.md'
              - 'CORS': 'user-guide/grpc/mid/cors.md'
              - 'Secure': 'user-guide/grpc/mid/secure.md'
              - 'CSRF': 'user-guide/grpc/mid/csrf.md'
      - 'labstack/echo':
          - 'Swagger UI': 'user-guide/echo/sw.md'
          - 'Common API': 'user-guide/echo/common.md'
          - 'API Docs': 'user-guide/echo/doc.md'
          - 'PPROF': 'user-guide/echo/pprof.md'
          - 'Prometheus client': 'user-guide/echo/prom.md'
          - 'Config': 'user-guide/echo/config.md'
          - 'Embed': 'user-guide/echo/embed.md'
          - 'Environment variable': 'user-guide/echo/env.md'
          - 'Error type': 'user-guide/echo/error-type.md'
          - 'App info': 'user-guide/echo/info.md'
          - 'Log': 'user-guide/echo/logging.md'
          - 'Multiple entries': 'user-guide/echo/multiple-entries.md'
          - 'Override boot': 'user-guide/echo/override.md'
          - 'Graceful shutdown': 'user-guide/echo/shutdown-hook.md'
          - 'Static file handler': 'user-guide/echo/static-file-handler.md'
          - 'TLS': 'user-guide/echo/tls.md'
          - 'Trace with logs': 'user-guide/echo/trace-with-logs.md'
          - 'Middleware':
              - 'Auth': 'user-guide/echo/mid/auth.md'
              - 'Logging': 'user-guide/echo/mid/logging.md'
              - 'Prometheus': 'user-guide/echo/mid/prom.md'
              - 'Tracing': 'user-guide/echo/mid/tracing.md'
              - 'RequestId': 'user-guide/echo/mid/meta.md'
              - 'Ratelimit': 'user-guide/echo/mid/ratelimit.md'
              - 'Timeout': 'user-guide/echo/mid/timeout.md'
              - 'Gzip': 'user-guide/echo/mid/gzip.md'
              - 'JWT': 'user-guide/echo/mid/jwt.md'
              - 'CORS': 'user-guide/echo/mid/cors.md'
              - 'Secure': 'user-guide/echo/mid/secure.md'
              - 'CSRF': 'user-guide/echo/mid/csrf.md'
      - 'gofiber/fiber':
          - 'Swagger UI': 'user-guide/fiber/sw.md'
          - 'Common API': 'user-guide/fiber/common.md'
          - 'API Docs': 'user-guide/fiber/doc.md'
          - 'PPROF': 'user-guide/fiber/pprof.md'
          - 'Prometheus client': 'user-guide/fiber/prom.md'
          - 'Config': 'user-guide/fiber/config.md'
          - 'Embed': 'user-guide/fiber/embed.md'
          - 'Environment variable': 'user-guide/fiber/env.md'
          - 'Error type': 'user-guide/fiber/error-type.md'
          - 'App info': 'user-guide/fiber/info.md'
          - 'Log': 'user-guide/fiber/logging.md'
          - 'Multiple entries': 'user-guide/fiber/multiple-entries.md'
          - 'Override boot': 'user-guide/fiber/override.md'
          - 'Graceful shutdown': 'user-guide/fiber/shutdown-hook.md'
          - 'Static file handler': 'user-guide/fiber/static-file-handler.md'
          - 'TLS': 'user-guide/fiber/tls.md'
          - 'Trace with logs': 'user-guide/fiber/trace-with-logs.md'
          - 'Middleware':
              - 'Auth': 'user-guide/fiber/mid/auth.md'
              - 'Logging': 'user-guide/fiber/mid/logging.md'
              - 'Prometheus': 'user-guide/fiber/mid/prom.md'
              - 'Tracing': 'user-guide/fiber/mid/tracing.md'
              - 'RequestId': 'user-guide/fiber/mid/meta.md'
              - 'Ratelimit': 'user-guide/fiber/mid/ratelimit.md'
              - 'JWT': 'user-guide/fiber/mid/jwt.md'
              - 'CORS': 'user-guide/fiber/mid/cors.md'
              - 'Secure': 'user-guide/fiber/mid/secure.md'
              - 'CSRF': 'user-guide/fiber/mid/csrf.md'
  - 'Developer guide': 'developer-guide/index.md'
  - 'Plugins': 'plugin.md'
  - 'Contribution':
      - 'Guide': 'contribution/guide.md'
      - 'Code of conduct': 'contribution/code-of-conduct.md'

extra_css:
  - stylesheets/extra.css
